services:
  # ---------- PostgreSQL ----------
  db:
    image: postgres:latest
    env_file: .env
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ---------- LocalStack (S3 mock) ----------
  s3-local:
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      SERVICES: s3
      DEFAULT_REGION: ${AWS_REGION}
    ports: ["4566:4566"]
    volumes:
      - s3data:/tmp/localstack

volumes:
  pgdata:
  s3data:
