spring:
  datasource:
    url: jdbc:tc:postgresql:16:///datashare
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: datashare
    password: datashare

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: it-test-secret

aws:
  region: test
  s3:
    bucket: it-test-bucket
