# Application configuration
spring:
  application:
    name: datashare-api
  datasource:
    url: jdbc:postgresql://datashare-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: true
      file: ../compose.yaml 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  web:
    resources:
        add-mappings: false
    error:
      whitelabel:
        enabled: false
        
server:
  port: ${API_PORT:8080}
security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here-change-in-prod-32-chars-min}
    expiration: ${JWT_EXPIRATION:900} # default 15 minutes
    issuer: ${spring.application.name}

aws:
  s3:
    endpoint: http://localhost:4566
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
  cors:
    allowed-origins: http://localhost:${WEB_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        type: INFO
      springframework:
        boot:
          docker: DEBUG
        web:
          servlet:
            mvc:
              method:
                annotation: DEBUG
          filter:
            CommonsRequestLoggingFilter: INFO
        security: DEBUG
    com:
      datashare:
        api: DEBUG
