spring:
  datasource:
    url: jdbc:h2:mem:unitdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: unit-test-secret

aws:
  region: test
  s3:
    bucket: unit-test-bucket
